app: 
  name: college-deploy

replicaCount: 2

image:
  repository: ashutosh4782/duniversity-college-portal-backend
  tag: latest

ports:
  containerPort: 3000

StatefulSet:
  app:
    name: mariadb-deploy
  replicaCount: 2
  image:
    repository: mariadb
    tag: 10.5
  ports:
    containerPort: 3306