apiVersion: apps/v1
kind: Deployment
metadata: 
  name: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: college
  template:
    metadata:
      labels: 
        app: college
    spec:
      containers:
      - name: college-cont
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        # 🔥 THIS IS THE MAIN CHANGE
        envFrom:
        - configMapRef:
            name: col-cfg
        - secretRef:
            name: col-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata: 
  name: college-svc
spec:
  selector: 
    app: college
  ports:
    - port: 3001
      targetPort: 3000
      protocol: TCP
  type: NodePort
