version: "3.8"

services:

  college-web:
    build: ./public/college-portal
    container_name: college-container

    ports:
      - "3016:3000"

    env_file:
      - .env

    depends_on:
      - mariadb

  mariadb:
    image: mariadb:11
    container_name: college-db

    environment:
      MARIADB_ROOT_PASSWORD: root123
      MARIADB_DATABASE: college_db

    ports:
      - "3306:3306"

    restart: always
