apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.5
        ports:
        - containerPort: 3306

        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: col-secret
              key: MARIADB_ROOT_PASSWORD

        volumeMounts:
        - name: mariadb-storage
          mountPath: /var/lib/mysql

        - name: initdb
          mountPath: /docker-entrypoint-initdb.d

      volumes:
      - name: mariadb-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc

      - name: initdb
        configMap:
          name: mariadb-init
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb   # ⚠️ MUST match DB_HOST
spec:
  selector:
    app: mariadb
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
